name: SmoothSSH Release - Zippy Zebra

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract Zippy Zebra Version
        id: get_version
        run: |
          LINE=$(grep "applicationVersion:" lib/screens/settings_screen.dart)
          FULL_STRING=$(echo "$LINE" | sed "s/.*'\(.*\)'.*/\1/")
          VERSION_ONLY=$(echo "$FULL_STRING" | cut -d' ' -f1)
          RELEASE_NAME=$(echo "$FULL_STRING" | cut -d'-' -f2- | xargs)
          
          echo "VERSION=$VERSION_ONLY" >> $GITHUB_ENV
          echo "REL_NAME=$RELEASE_NAME" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Android Artifacts
        run: |
          flutter build appbundle --release --no-codesign
          flutter build apk --release --no-codesign

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "SmoothSSH: ${{ env.REL_NAME }}"
          tag_name: ${{ github.ref_name }}
          body: |
            ### Release: ${{ env.REL_NAME }}
            **App Version:** ${{ env.VERSION }}
            
            **Automated Build Features:**
            - Gesture-based multi-session swiping
            - Session Transcript & Paste logic
            - AES-Encrypted Vault
            - Pixel 9 Pro XL Optimized rendering (Since this is the device I have access to)
          files: 
            build/app/outputs/bundle/release/app-release.aab
            build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
